name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Ensures only one deploy runs; older in-progress runs get canceled
concurrency:
  group: swa-prod
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"        # your files are in the repo root
          api_location: ""         # no API
          output_location: ""      # no build output folder
          skip_app_build: true     # skip Oryx build & speed things up
